---
-   name: Provision Site
    hosts: all
    remote_user: root
    vars:
      certbot_email: support@loadcrm.ru
      certbot_hosts:
        - demo.loadcrm.store
        - api.loadcrm.store
    tasks:
      -   name: Update apt packages
          apt:
            update_cache: yes
      -   import_tasks: tasks/setup_docker.yml
      -   import_tasks: tasks/setup_certbot.yml
      -   import_tasks: tasks/generate_certificates.yml
    handlers:
      -   name: Start docker on boot
          systemd:
            name: docker
            state: started
            enabled: yes